version: '3'
services:
  # 信令服务器
  signaling-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: signaling-server
    restart: always

    # Nginx 服务
  nginx:
    image: nginx:latest
    ports:
      - "8000:443"
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
      - ./html:/usr/share/nginx/html
    depends_on:
      - signaling-server
    restart: always

